### ISSUE TITLE
[TRACKER] Implementation

### ISSUE THREAD

**Issue by razcore-rad** [GDQuest/godot-2d-tactical-space-combat#2]
List of features to be implemented:

- [x] Path finding
- [x] Doors
- [ ] Weapons
- [ ] Shields
- [ ] Helm with evasion
- [ ] Sensors
- [ ] Fire
- [ ] Oxygen depletion
- [ ] Power management
- [x] Enemy ship
- [x] Unit box selection
- [ ] UI

# Bugs

- [x] Fix unit moving across doors at the same time #1

**Comment by razcore-rad** [comment]
Closed by mistake
